### ISSUE TITLE
Video recording does not work

### ISSUE THREAD

**Issue by AlexanderLukashin** [yasirkula/UnityNativeCamera#120]
After the user finishes recording the video, null is returned instead of the path.

- Unity version: 2022.3.29f
- Platform: Android
- Device: Redmi 10 (Android 13, MIUI 14.0.2), Xiaomi 14 (Android 14, HyperOS 1.0.6.0)
![image](https://github.com/yasirkula/UnityNativeCamera/assets/40304767/34cb871d-3edc-4862-a5bc-14ddd6ff2ce1)
[Link to the log file](https://1drv.ms/u/c/90b326376bedf8a3/EdO7ybLHC7xAix6IUtWYr6YBw3DvIVhTEETe30X0ouJDXg)

**Comment by yasirkula** [comment]
May I see your code?

**Comment by AlexanderLukashin** [comment]
Here is the method for processing pressing the start recording button
```c#
        private void RecordVideo(ClickEvent eventArgs)
        {
            _ = NativeCamera.RecordVideo(Record);

            void Record(string path)
            {
                AddFiles(_data.TaskMedia, path).Forget();
            }
        }
```

**Comment by yasirkula** [comment]
Hmm, it looks good to me. We need to figure out whether this is a device-specific issue or Unity version-specific issue. Do you have older Unity versions that you can test the [example code](https://github.com/yasirkula/UnityNativeCamera?tab=readme-ov-file#example-code) on?

**Comment by AlexanderLukashin** [comment]
I tried to build in Unity 2021.3.38f, but the path is still returned null. [Link to the log file](https://1drv.ms/u/c/90b326376bedf8a3/Eaf9OXioS-RDlgzgoURejU0BxUZOYRF6DQv_5mgIk4qG-Q)

**Comment by AlexanderLukashin** [comment]
This bug is also reproduced on the Galaxy tab 8 tablet (Android 14, OneUI 6.0)

**Comment by yasirkula** [comment]
I've created the APK inside [this zip archive](https://github.com/yasirkula/UnityNativeCamera/files/15387442/Test.zip) on 2021.3.29f1 using Mono (faster build) and it works well on my Galaxy S8. Could you give it a try? Source code:

```csharp
NativeCamera.Permission permission = NativeCamera.RecordVideo( ( path ) =>
{
	if( path != null )
	{
		// Play the recorded video
		Handheld.PlayFullScreenMovie( "file://" + path );
	}
} );
```

**Comment by AlexanderLukashin** [comment]
It doesn't work again, here is a [link](https://1drv.ms/u/c/90b326376bedf8a3/ERUz1saAABVGg_ftSzrVQZYBqs4QJFsd1jiqddUEfK2LGQ) to the archive with videos and logs

**Comment by yasirkula** [comment]
Thank you, it's evidently a device-specific issue. I'll investigate it.

**Comment by AlexanderLukashin** [comment]
There is no such error in the plugin version 1.4.2, maybe it will help somehow

**Comment by yasirkula** [comment]
I've been having a busy schedule so I couldn't take a look at it yet.

**Comment by yasirkula** [comment]
I've now added a few extra logs to the sections of the code that were added in v1.4.3. Reading those logs could prove useful. Could you replace NativeCamera.aar with the one [inside this zip archive](https://github.com/user-attachments/files/15913546/NativeCamera.zip) and post all logcat logs that have the log tag "Unity"?

PS. The issue doesn't occur on an Android 14 Galaxy S23 device either.

**Comment by AlexanderLukashin** [comment]
[Xiaomi-22011119UY-Android-13_2024-06-21_110356.zip](https://github.com/user-attachments/files/15924297/Xiaomi-22011119UY-Android-13_2024-06-21_110356.zip)

**Comment by yasirkula** [comment]
OK I think I figured it out. Thank you for providing the logs. The issue is, the video is saved to path X (that we provide to the camera) but Android wraps that path inside a Uri, let's call it Y. Normally, the native GetPathFromURI function can convert Y to X but for unknown reasons, this failed on your Xiaomi device. The fallback to this scenario is, copying the file from Y to a filepath that we provide (this behaviour was added in v1.4.3). The thing I overlooked is, I was passing back X to that filepath. So, NativeCamera was trying to copy the video from X back to X.

I've resolved this issue in two steps:

- If conversion from Y to X fails, I also check if there is a non-empty file existing at X (behaviour in v1.4.2). If so, then it means that the video was recorded to X successfully and we can simply return X
- In the worst case, if the "copy file" fallback is reached, I copy the file to a different path than X to avoid collisions

Could you give [this new aar file](https://github.com/user-attachments/files/15936051/NativeCamera.zip) a shot and verify that the issue is resolved? I'd also appreciate if you could send the Unity-tagged logs one last time to make sure that nothing goes wrong.

**Comment by AlexanderLukashin** [comment]
These changes have fixed the bug.
[Xiaomi-23127PN0CG-Android-14_2024-06-24_110638.zip](https://github.com/user-attachments/files/15951443/Xiaomi-23127PN0CG-Android-14_2024-06-24_110638.zip)
