### ISSUE TITLE
Native Camera restarts app after taking photo on certain devices

### ISSUE THREAD

**Issue by HNKMaster** [yasirkula/UnityNativeCamera#27]
Hi. I'm using this plugin, which works very well, but I'm having issues with certain phones (Samsung A10 for example). On certain busy scenes, when I call the Native Camera plugin and take the picture, the app restarts. I suspect memory issues while the app is in Background.

**Comment by yasirkula** [comment]
I'm guessing the same. Unfortunately, I can't resolve this issue since I can't prevent Android OS from killing the background apps (in this case, Unity). In native Android apps, *Activity* classes have certain callback functions that lets them save their data but it is not possible to do so in a Unity app.
