### ISSUE TITLE
Ability to choose from photo gallery

### ISSUE THREAD

**Issue by shunia** [yasirkula/UnityNativeCamera#33]
I thinks it's common to choose from gallery or just take a photo in place when using camera.
Can this be added to you library please?

It could be used like: 
```c#
// Call this function will open users default photo gallery, when user taps any file, return the file path
// (or maybe we need to copy it into our app's cache directory, not android expert here sorry), 
// then return the file path
NativeCamera.OpenGalleryAndChoose((string path) => 
{ 
  Texture2D texture = NativeCamera.LoadImagePath(path);
});
```

**Comment by yasirkula** [comment]
I don't want to implement this feature for these reasons:

1. It requires NativeCamera and NativeGallery simultaneously, can be confusing for some users
2. But more importantly, TakePicture and GetImageFromGallery functions have unique parameters. I'd need to either omit them or add a long list of parameters to the OpenGalleryAndChoose function
3. Implementing OpenGalleryAndChoose means that I'll have to create a UI where user selects either camera or gallery. I don't want that since developers would probably need to modify it to match their UI style or support localization, in which case, it is the same as creating the UI from scratch

It'd be much better for developers to create their own UI with 2 buttons and call the corresponding NativeGallery and NativeCamera functions upon click.

**Comment by shunia** [comment]
Well, my idea is a standalone API, to open the gallery, return the image user choosed. There is no modification of the `TakePicture` function. And it shouldn't be combined into one API, like this:
```
// NativeCamera.cs
static void TakePicture() {}

// NativeGallery.cs
static void OpenAndChoose() {}
```
Since it's a added API, user should not be confused. They should choose the right API according to there needs.

 No UI needed of course, user **must** implement their own UI for the choose widget. 

I understand the work behind this function, it requires a lot of hard work on both android side and iOS side, and the docs needs to be updated, and a lot of explanation for not offering UI cause user may want a default one, etc. 

Just think it could be a create plus to this library if it's implemented.

**Comment by yasirkula** [comment]
NativeGallery.GetImageFromGallery and NativeCamera.TakePicture are standalone functions, they both return the image path in a callback. So unless I am misunderstanding you, users can call these functions upon button clicks and everything should work smoothly.

**Comment by shunia** [comment]
Oh, just found out that there's `NativeGallery` did this. Sorry I come from the unity forum and did not searched for your other repos, though it could be all in one. 
My bad, closing this.

And really thanks for your library, works great!
