### ISSUE TITLE
more control about video dimensions

### ISSUE THREAD

**Issue by are-chris** [yasirkula/UnityNativeCamera#38]
Hi yasirkula,

we are using your plugin on iOS and android and up to now we like it very much.

However on Android we face the problem that the videos are too big when we use the default camera quality option (RecordVideo function).
We tried all other quality settings, but these are of no help either, please see our results: (gathered with Xiaomi MI 8 Lite)

Default: 1920x1080 -> 12 sec results in ~26MB (too big)
Low: 176x144 -> 12 sec results in 287KB (quality not satisfying)
Medium: 3840x2160 -> 3 sec video results in ~14 MB (too big)
High: 3840x2160  -> 2 sec video results in ~12.3 MB (too big) (resolution is similar to medium, is that how it should be?)

Would it be possible to have more fine granular control about the capture resolution?
For example ask for a specific resolution and get the nearest to that (either upwards or downwards)

Cheers,
Christian

P.S. On iOS (iPhone 5SE) we get pretty usable results in Default quality with 480x360 12 sec resulting in 1.3 MB <- perfect to use

**Comment by yasirkula** [comment]
On Android, [EXTRA_VIDEO_QUALITY](https://developer.android.com/reference/android/provider/MediaStore#EXTRA_VIDEO_QUALITY) setting is used. Since it supports only 2 values, I've decided to use the same value for both Medium and High.

NativeCamera uses ACTION_VIDEO_CAPTURE Intent to capture videos and it doesn't seem possible to set a resolution using this method. You probably need a plugin that uses Android's native Camera API.
