### ISSUE TITLE
Recording Audio and Playing it in Scene

### ISSUE THREAD

**Issue by cyberjj999** [yasirkula/UnityNativeCamera#51]
Hey Yasirkula. Thanks for yet another great plugin! I actually have a simple question that may span across different asset that you have uploaded on the Unity Asset Store so I hope this platform works well.

I would like to
1) Allow user to upload audio file
2) Allow user to record audio (and eventually play it in my unity scene for the user to hear it)

Based on research, it seems like there is support for uploading audio files in UnityNativeGallery (https://github.com/yasirkula/UnityNativeGallery/issues/129) => However, it only works with Android.
You suggested using UnityNatieFilePicker to get Audio Files instead, since it supports both IOS and Android - I just wanted to clarify if this is true.

Edit: I am able to use UnityNativeFilePicker to grab audio file now - using audoFileType = "audio/*", which did not include OGG and some other format - once again, not a big deal but should I need to work with i.e. OGG, do I have to add in myself?
Also, whilist I am able to grab the path to the audio file, it seems like playing it in Unity requires using
```UnityWebRequestMultimedia.GetAudioClip(path, AudioType.SomeAudioType);```
This requires me to know the specific audio type from the file path - I have a hackish solution with is to use .split and get the file extension by checking the last element after splitting it with ".", but are there any ways supported for to know the file type user selected?

For recording of audio, I don't think you mentioned anywhere about it in UnityNativeCamera. I'm just wondering if its a feature that is supported, since I would think its quite similar to Video and Pictures - i.e. we need to request microphone access and then allow users to record.

On a side note, I'm just wondering if its possible for the plugin to record by holding down a button and releasing when user is done, instead of the traditional camera set up. This isn't a big problem to me, but I'm just wondering the possibility.

Thank you very much for taking the time to read this!

**Comment by yasirkula** [comment]
> You suggested using UnityNativeFilePicker to get Audio Files instead

Yes, this is the only multi-platform solution I have.

> using audoFileType = "audio/*", which did not include OGG

Its mime type is `audio/ogg`, so I'm surprised that OGG files aren't included in the list. I really can't tell why.

> but are there any ways supported for to know the file type user selected

There isn't a built-in solution. I'd have followed the same path you've followed.

> Can we record audio with NativeCamera

Unfortunately not. AFAIK, audio recording API is irrelevant to camera API, so I didn't think about implementing this feature. I still don't, to be honest.

> I'm just wondering if its possible for the plugin to record by holding down a button and releasing when user is done

NativeCamera just launches the native camera app when RecordVideo is called. Afterwards, the native camera app handles inputs on its own, i.e. doesn't receive input from Unity. It's actually impossible for it to receive input from Unity on Android because there can only be one Activity running at a time and that is the native the camera app's Activity, Unity Activity is frozen in the meantime.

**Comment by cyberjj999** [comment]
Hey @yasirkula , Thanks very much for the response. I appreciate your explanation as it makes things much clearer. Regarding  Audio Recording API, I suppose I can try to look around to see if there's another asset that can support this feature, but just curious, how difficult would it be for me to add on in your current plugin for this Audio Recording feature?

If its a lot of work then I suppose I will just focus on looking for other solution, else I may try to add on a simple functionality on top of your plugin.

**Comment by yasirkula** [comment]
For audio recording, you can check out tutorials about Unity's [Microphone API](https://docs.unity3d.com/ScriptReference/Microphone.html). Otherwise, I don't know how long it would take to create a native audio recording plugin. My native plugins took a lot of time for me to create and then more time to fix the issues reported by users. You can also search for plugins on GitHub and [Asset Store](https://assetstore.unity.com/packages/tools/integration/natdevice-media-device-api-162053).

To load audio files without using UnityWebRequest, you can search for plugins on Asset Store, e.g. [this](https://assetstore.unity.com/packages/tools/audio/audioimporter-146746).

**Comment by cyberjj999** [comment]
Thanks for the links! I genuinely appreciate it! Although I'm still figuring out a way to record audio, I have found a way to load audio already, will just comment here in case anyone needs it the future.

```public class NativePluginManager : MonoBehaviour
{
	private string audioFileType = "audio/*";               // Grab all audio file type (apparently OGG is not part of this, unsure why)
	private string oggFileType;								// Store the OGG File Type		
		
	public AudioSource audioSource;							// Create a empty game object, add the AudioSource component and drag it into this variable in the inspector
	AudioClip myClip;
	

	private void Start()
	{				
		oggFileType = NativeFilePicker.ConvertExtensionToFileType("ogg"); // Grab the OGG type (don't need this if you don't want OGG file type)
    }		
	
	public void PickAudio()
		{
			// Pick an audio file
			NativeFilePicker.Permission permission = NativeFilePicker.PickFile((path) =>
			{
				Debug.Log("Picked file: " + path);
				if (path == null)
					Debug.Log("Operation cancelled");
				else
				{
					string filePath = "file:///" + path;								// We need to add file:// to ensure that the file can be played in Android & IOS
					// string sampleMusic = "https://ciihuy.com/downloads/music.mp3"; 	// Replace filePath with sampleMusic to test if you want to
					StartCoroutine(GetAudioClip(filePath));
				}
			}, new string[] { audioFileType, oggFileType });
			
		}
	
	// This method will get the audio clip and play it
	IEnumerator GetAudioClip(string path)
    {
        using (UnityWebRequest www = UnityWebRequestMultimedia.GetAudioClip(path, AudioType.MPEG))
        {
            yield return www.SendWebRequest();
 
            if (www.isNetworkError)
            {
                Debug.Log(www.error);
            }
            else
            {
                myClip = DownloadHandlerAudioClip.GetContent(www);
                audioSource.clip = myClip;
                audioSource.Play();
                Debug.Log("Audio is playing.");
            }
        }
    }
          
	// You can create a button to pause the audio, use this method when onclick
    public void pauseAudio(){
        audioSource.Pause();
    }
    
	// You can create a button to play/replay the audio, use this method when onclick	
    public void playAudio(){
        audioSource.Play();
    }
}```
Source: https://thirteenov.ciihuy.com/how-to-play-an-mp3-audio-file-from-url-in-unity/
[ Youtube Video included in the source link ] 

@yasirkula Cheers and I'll close this thread for now =)
