### ISSUE TITLE
does this plugin has a minimum android sdk version it can work for?

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeCamera#52]
**Description of the bug**
i am asking since after i updated my plugins to its latest version, and I build the project again, I receive error of unsuccessful build because of fail of gradle.

popup saying: "android linkage issue. see console."
console saying: "Exception while marshalling "<specific path to my Asset project folder>" Probably the SDK is read-only "

**Platform specs**
- Unity version: 2019 LTS
- Platform: Android. 
- Minimum Software level is 6 marshmello
- How did you download the plugin: Asset Store

**Comment by yasirkula** [comment]
It doesn't have a minimum requirement. Does removing NativeCamera.aar for testing purposes resolve the issue?

**Comment by shacharoz** [comment]
good thinking.
i am using both camera, gallery and share. share was not changed. actually
I did change the gallery code.

its quite a lot of work to remove the camera and gallery in order to try
that, but you have a point.
i will try

**Comment by yasirkula** [comment]
You can temporarily move the aar files to desktop and after building your project, move them back to their original folders. You are just testing if these plugins are affecting the build.

**Comment by shacharoz** [comment]
aw great!
let me check immediately

**Comment by shacharoz** [comment]
hi man, it actually worked!
the build is now successful!
what does it mean?
i will add one by one to find the specific one that stops me?

>

**Comment by yasirkula** [comment]
Yes, it would be helpful.

**Comment by shacharoz** [comment]
ok. found the error source is with the native gallery actually.

do you prefer to remove this issue and I will try to open it on gallery?
i will go deeper into the places I changed the code lately. give me another
few minutes

Shachar Oz
Design & Business for
Emergent Tech Products
flux-experiences.com/design
Portfolio <https://behance.net/shacharoz>  | +39-351-519-0003

**Comment by yasirkula** [comment]
Can you check the build error messages and see if there are any other useful information there? You can copy&paste the messages here, if you like.

**Comment by shacharoz** [comment]
after reimporting all the arr files with the package manager, I tried again.
i thought that might have been my issue, but its not.

here are some of the meaningful errors.

> Android resource linking failed
>
Temp\gradleOut\launcher\build\intermediates\merged_manifests\release\AndroidManifest.xml:52:
AAPT: error: attribute android:requestLegacyExternalStorage not found.
> error: failed processing manifest.
> try: Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full
insights.


is this helpful enough? what happened to the manifest file?

**Comment by yasirkula** [comment]
I've updated the [FAQ](https://github.com/yasirkula/UnityNativeGallery/#faq). Please see the 3rd entry.

**Comment by shacharoz** [comment]
ok.
i assume you mean this:

   - Android build fails, it says "error: attribute
   android:requestLegacyExternalStorage not found" in Console

i wonder how I came to that situation all of a sudden...:)

anyway, I opened, edited. now how do I close again to be arr? just zip and
change the extension?

**Comment by yasirkula** [comment]
Because I've added `android:requestLegacyExternalStorage` to AndroidManifest with the latest update. When you open NativeGallery.aar with WinRAR or 7-Zip and modify a file inside it, upon returning to the opened NativeGallery.aar file, WiRnRAR/7-Zip will prompt you to apply the changes to the archive.

**Comment by shacharoz** [comment]
that's it!
thanks man.
its fixed.

**Comment by shacharoz** [comment]
> Failed to transform artifact 'NativeGallery.aar (:NativeGallery:)' to
match attributes {artifactType=android-manifest}

actually not.
i had the nativegallery file with .arr instead of .aar
now it gives me this error.

i might have closed it wrong. i will try as you said.

Shachar Oz
Design & Business for
Emergent Tech Products
flux-experiences.com/design
Portfolio <https://behance.net/shacharoz>  | +39-351-519-0003


‪On Tue, Jan 19, 2021 at 11:45 PM ‫Shachar Oz , שחר עוז‬‎ <
shachar.oz@gmail.com> wrote:‬

> that's it!
> thanks man.
> its fixed.
>
>
> On Tue, Jan 19, 2021 at 6:14 PM Süleyman Yasir KULA <

**Comment by shacharoz** [comment]
ok. worked after i opened the aar on a visual zip (without extracting the
package), updated the XML file, return the XML file into the visual editor
(and it will recompile). then close the zip and get back to unity.



‪On Tue, Jan 19, 2021 at 11:54 PM ‫Shachar Oz , שחר עוז‬‎ <
shachar.oz@gmail.com> wrote:‬

>    > Failed to transform artifact 'NativeGallery.aar (:NativeGallery:)' to
> match attributes {artifactType=android-manifest}
>
> actually not.
> i had the nativegallery file with .arr instead of .aar
> now it gives me this error.
>
> i might have closed it wrong. i will try as you said.
>
> Shachar Oz
> Design & Business for
> Emergent Tech Products
> flux-experiences.com/design
> Portfolio <https://behance.net/shacharoz>  | +39-351-519-0003
>
>
> ‪On Tue, Jan 19, 2021 at 11:45 PM ‫Shachar Oz , שחר עוז‬‎ <
> shachar.oz@gmail.com> wrote:‬
>
>> that's it!
>> thanks man.
>> its fixed.
>>
>>
>> On Tue, Jan 19, 2021 at 6:14 PM Süleyman Yasir KULA <

**Comment by yasirkula** [comment]
That's also how I modify aar files. Good to hear 😃

**Comment by gamedust-ph** [comment]
Hi yasirkula why did you add android:requestLegacyExternalStorage?

**Comment by yasirkula** [comment]
NativeCamera doesn't have android:requestLegacyExternalStorage.

**Comment by gamedust-ph** [comment]
android:requestLegacyExternalStorage this add was add in NativeGallery . It is causing android failure in our alpha application. 
When I tried to edit androidmanifest and remove <app android:requestLegacyExternalStorage but more error are coming up. This is not appearing before but when I upgrade it is failing the build.

**Comment by yasirkula** [comment]
"requestLegacyExternalStorage" fixes a rare UnauthorizedAccessException on Android 10. The best way forward is to update your Android SDK so that requestLegacyExternalStorage works properly. You'll have to update your SDK in a few months anyways if you want to release your game to Google Play. If for some reason it is impossible to update the SDK, then the final contents of modified AndroidManifest.xml should look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="com.yasirkula.unity">
	<uses-sdk android:targetSdkVersion="4" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="replace" />
</manifest>
```

**Comment by gamedust-ph** [comment]
Hi Yasirkula,

Thanks I have updated the androidmanifest.xml. The problem is that sdkbox utilize only api 28 sdk android.  
I have to rollback to api 28 sdk.  Merge NativeGallery and SDKBox is very powerful tool to create features. 

https://discuss.cocos2d-x.org/t/sdkbox-admob-not-working-in-api-29-android/48129

**Comment by wesclarkemag** [comment]
Hi @yasirkula 

We are using this plugin, thank you for your efforts. We're now dealing with Google asking us to remove requestLegacyExternalStorage from our application as this is considered legacy for apps built against API level 30 and above. What are the best practices here? We want to keep supporting older devices. Are you suggesting that the bug you referenced this is fixed with an SDK update? i.e _"requestLegacyExternalStorage" fixes a rare UnauthorizedAccessException on Android 10_

Googles statement on this is: _Developers with apps on devices running Android 11+ must use Scoped Storage so users have more access control over their device storage._ 

Have you had to deal with this previously, and if so, what is the approach?

**Comment by yasirkula** [comment]
requestLegacyExternalStorage has no effect on Android 11+ and is even recommended by Google if we want to opt out of scoped storage on Android 10 devices: https://developer.android.com/about/versions/11/privacy/storage#media-file-access. So you have nothing to worry about.

**Comment by wesclarkemag** [comment]
Hi @yasirkula thanks for your quick response. 

The problem we appear to be having is that Google no longer wants this permissions to be included in Apps targeting Android 11 or later. Image attached:

![Screenshot 2021-04-12 at 15 51 41](https://user-images.githubusercontent.com/62353443/114414990-35d61b80-9ba7-11eb-9a7d-573f2cce65c4.png)

In our case, removing this flag from the AndroidManifest results in the user being denied permission to access a file in the Gallery on Android 10 only. Android 7,8,10,11 all appear to work fine. Our Unity version is 2019.5.15f1, will update with more information as I get it.

**Comment by yasirkula** [comment]
It must be a very recent announcement because I can't find anything about it on google yet. Even though the text mentions '_requestLegacyExternalStorage_' once, the whole text talks about **All Files Access** permission which isn't related to requestLegacyExternalStorage at all. The text also constantly mentions **Android 11+** but [requestLegacyExternalStorage is officially documented to have no effect on Android 11](https://developer.android.com/about/versions/11/privacy/storage#scoped-storage), it affects only Android 10. I continue to believe that requestLegacyExternalStorage won't cause the app to be removed from Google Play because:

- it affects only Android 10, this text talks about Android 11+
- it isn't related to All Files Access permission (MANAGE_EXTERNAL_STORAGE). That permission is part of Android 11+, not Android 10
- if they were to forbid the use of requestLegacyExternalStorage on Android 10, then apps couldn't access media files using File API on Android 10. After they initially removed File API completely on Android 10's release, there was a significant backlash from the developers and they had to add it back for media files on Android 11. Now, all Android versions except Android 10 natively support File API for media files. _requestLegacyExternalStorage_ is **the key element** that gives Android 10 the ability to access media files using File API, too. Without requestLegacyExternalStorage, developers would have to use SAF just for Android 10 but I'd like to remind you again that this was the main reason of the backlash from the developers that resulted in them adding File API support for media files on Android 11

**Comment by yasirkula** [comment]
Discussion continued at https://github.com/yasirkula/UnityNativeGallery/issues/182
