### ISSUE TITLE
读取图片失败

### ISSUE THREAD

**Issue by TastSong** [yasirkula/UnityNativeCamera#55]
建议将Texture2D LoadImageAtPath( string imagePath, int maxSize = -1, bool markTextureNonReadable = true,
		bool generateMipmaps = true, bool linearColorSpace = false )中的markTextureNonReadable  默认值改成false，要不会导致加载图片到Rawimage失败

**Comment by yasirkula** [comment]
Thank you for the feedback. I don't want to make this change because setting markTextureNonReadable to false increases the RAM usage of the Texture and it isn't needed for common use-cases. Also, you don't need to set it to false for RawImage, calling `rawImage.texture = NativeGallery.LoadImageAtPath(path,maxSize);` works perfectly fine.

**Comment by TastSong** [comment]
Thank you very much for your reply

**Comment by TastSong** [comment]
My primary Unity skill improved because of your reply.LOL~
