### ISSUE TITLE
APP Breakdown when i take more than 6 Photos

### ISSUE THREAD

**Issue by Akira8707** [yasirkula/UnityNativeCamera#72]
the app breakdown when i use to take more than 6 photos ,it both happens in ios or andriod

my code is 
![image](https://user-images.githubusercontent.com/85773014/124926000-a0281c00-e02f-11eb-9fb1-f509d93c0588.png)

Does the plug-in has this limitation，how can i improve it。
Or i want to know how to deal this problem ,my project needs to take more than ten photos.

**Comment by yasirkula** [comment]
Cameras can captures photos in ultra HD resolutions. If you import them as is to Unity, they will consume literally hundreds of MBs (combined). It's expected for an app to crash due to insufficient memory at that point. What you can do is, call **NativeCamera.LoadImageAtPath** with a small maxSize parameter to create your Textures, so don't use LoadImage.

**Comment by Akira8707** [comment]
i have change maxSize to 256，and markTextureNonReadable to false(i need to encode this textures to upload to server)，and i have take more than 10 photos ，and it run well

very thankful

**Comment by yasirkula** [comment]
You are welcome!
